apiVersion: v1
kind: Service
metadata:
  name: webapp
  # namespace: bmi
  labels:
    app: webapp
spec:
  ports:
  - port: 8889
    targetPort: 8889
    name: http
  # externalIPs: [192.168.43.70]
  selector:
    app: webapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  # namespace: bmi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: debug
                operator: Exists
      containers:
      - name: webapp
        image: bmi/webapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8889
---

